### ISSUE TITLE
Is this ready for use

### ISSUE THREAD

**Issue by BibinQA** [PerfectoCode/perfecto-cypress-sdk#12]
Hello,

Checking if this is ready to use and test? If it is ready, can we have some examples for how we can do this?

**Comment by elhay-av** [comment]
Hi @BibinQA 

It is not ready to use. please follow Perfecto [release notes](https://developers.perfectomobile.com/display/PD/Release+notes) to be updated once it released.

You should be able to find information on how to use this package in the [README.md](https://github.com/PerfectoCode/perfecto-cypress-sdk/blob/master/README.md) file

**Comment by BibinQA** [comment]
Do you have any ETA on this?

**Comment by elhay-av** [comment]
This integration is currently in Beta phase and only available in select private clouds. If interested, [contact Perfecto Support](http://support.perfecto.io/).
